[project]
name = "orchid-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.21.0",
    "openai>=1.71.0",
    "python-dotenv>=1.1.0",
]
